spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false

app:
  telegram:
    enabled: true
    bot-token: ${TELEGRAM_BOT_TOKEN}
  earthquake:
    poll-interval-ms: 30000

logging:
  level:
    com.depremnobetcisi: INFO
